const vscode = require('vscode');
const fs = require('fs');
const os = require('os');
const path = require('path');
const crypto = require('crypto');
const https = require('https');
const http = require('http');

// Hooks in ~/.claude/settings.json run a tiny helper script that appends one
// JSON line to these files when a Claude Code request finishes (Stop) or when
// Claude is waiting for the user (Notification). All notification logic lives
// here in the extension.
const claudeDir = path.join(os.homedir(), '.claude');
const settingsPath = path.join(claudeDir, 'settings.json');
const hookScriptPath = path.join(claudeDir, 'claude-notify-hook.js');

const DONE = 'done';
const WAITING = 'waiting';

const TRIGGERS = {};
TRIGGERS[DONE] = '.ntfy-trigger';
TRIGGERS[WAITING] = '.ntfy-trigger-waiting';

const MARKER_PREFIX = '.ntfy-seen-';

// Notification types that are not "Claude is waiting for you".
const SKIP_NTYPES = { auth_success: true };

const REQUEST_TIMEOUT_MS = 8000;
const POLL_INTERVAL_MS = 3000;
const SWEEP_EVERY_TICKS = 20; // ~ every 60s

// ntfy's JSON "priority" field is an integer 1..5; expose friendly names.
const PRIORITY_MAP = { min: 1, low: 2, default: 3, high: 4, max: 5 };

// The helper script the hooks invoke. It reads the hook payload Claude Code
// sends on stdin and records exactly what the extension needs to (a) name the
// project and (b) dedupe by a per-request id. Kept tiny and dependency-free.
const HOOK_SCRIPT = [
  '// Auto-generated by the "Claude Notify" VS Code extension. Do not edit;',
  '// it is rewritten on every activation.',
  "const fs = require('fs');",
  "const os = require('os');",
  "const path = require('path');",
  "const kind = process.argv[2] === 'waiting' ? 'waiting' : 'done';",
  "const name = kind === 'waiting' ? '.ntfy-trigger-waiting' : '.ntfy-trigger';",
  "const file = path.join(os.homedir(), '.claude', name);",
  "let s = '';",
  "process.stdin.on('data', function (d) { s += d; });",
  "process.stdin.on('end', function () {",
  '  let j = {};',
  "  try { j = JSON.parse(s || '{}'); } catch (e) { /* ignore */ }",
  '  const rec = {',
  '    kind: kind,',
  "    project: process.env.CLAUDE_PROJECT_DIR || j.cwd || '',",
  "    id: j.prompt_id || '',",
  "    session: j.session_id || '',",
  "    transcript: j.transcript_path || '',",
  "    ntype: j.notification_type || '',",
  "    reason: j.stop_reason || ''",
  '  };',
  "  try { fs.appendFileSync(file, JSON.stringify(rec) + '\\n'); } catch (e) { /* ignore */ }",
  '});',
  'process.stdin.resume();',
  '',
].join('\n');

function cfg() {
  return vscode.workspace.getConfiguration('claudeNotify');
}

function isEnabled() {
  return cfg().get('enabled', true);
}

function triggerPath(kind) {
  return path.join(claudeDir, TRIGGERS[kind]);
}

// How long a sent event stays remembered so a duplicate firing of the *same*
// event is suppressed. With an exact key this can be generous - it never drops
// a distinct event. 0 disables cross-window dedup.
function retentionMs() {
  const seconds = Number(cfg().get('dedupeSeconds', 60));
  return isFinite(seconds) && seconds > 0 ? seconds * 1000 : 0;
}

// True if ~/.claude/settings.json has our Stop hook wired up.
function hooksConfigured() {
  try {
    const d = JSON.parse(fs.readFileSync(settingsPath, 'utf8'));
    const stop = d && d.hooks && d.hooks.Stop;
    return (
      Array.isArray(stop) &&
      stop.some(function (g) {
        return (
          g &&
          Array.isArray(g.hooks) &&
          g.hooks.some(function (h) { return h && isOurHook(h.command); })
        );
      })
    );
  } catch (e) {
    return false;
  }
}

// Reflect health in the status bar: a warning when enabled but misconfigured,
// so "looks on but nothing arrives" becomes visible instead of silent.
function render(item) {
  const c = cfg();
  if (!c.get('enabled', true)) {
    item.text = '$(bell-slash) Claude';
    item.tooltip = 'Уведомления на телефон выключены. Нажмите, чтобы включить.';
    item.color = new vscode.ThemeColor('disabledForeground');
    return;
  }
  if (!String(c.get('topic', '') || '').trim()) {
    item.text = '$(warning) Claude';
    item.tooltip =
      'Claude Notify: топик не задан — уведомления не отправляются. ' +
      'Задайте claudeNotify.topic в настройках (Ctrl+,).';
    item.color = new vscode.ThemeColor('statusBarItem.warningForeground');
    return;
  }
  if (!hooksConfigured()) {
    item.text = '$(warning) Claude';
    item.tooltip =
      'Claude Notify: хуки Claude Code не настроены — уведомления не придут. ' +
      'Выполните команду «Claude Notify: настроить хуки Claude Code».';
    item.color = new vscode.ThemeColor('statusBarItem.warningForeground');
    return;
  }
  item.text = '$(bell) Claude';
  item.tooltip = 'Уведомления на телефон включены. Нажмите, чтобы выключить.';
  item.color = undefined;
}

// Replace {project} in a title/message. When the project is unknown the
// placeholder collapses and any separator it left behind is tidied away, so
// "Claude Code · {project}" degrades to "Claude Code".
function applyPlaceholders(text, project) {
  const raw = String(text || '');
  const hadPlaceholder = /\{project\}/.test(raw);
  let out = raw.replace(/\{project\}/g, project || '');
  if (hadPlaceholder && !project) {
    out = out.replace(/\s*[-–—·:|,]+\s*$/, '').replace(/^\s*[-–—·:|,]+\s*/, '');
  }
  return out.replace(/\s{2,}/g, ' ').trim();
}

function projectName(dir) {
  const d = String(dir || '').trim();
  if (!d) {
    return '';
  }
  return path.basename(d.replace(/[\\/]+$/, ''));
}

// Parse the claimed trigger contents into event records. Each line is one JSON
// object written by the hook script; a non-JSON line is treated as a bare
// project path from an older, simpler hook.
function parseTrigger(content) {
  return String(content || '')
    .split(/\r?\n/)
    .map(function (s) { return s.trim(); })
    .filter(function (s) { return s.length > 0; })
    .map(function (line) {
      if (line.charAt(0) === '{') {
        try {
          const j = JSON.parse(line);
          return {
            project: j.project || '',
            id: j.id || '',
            session: j.session || '',
            transcript: j.transcript || '',
            ntype: j.ntype || '',
            reason: j.reason || '',
          };
        } catch (e) { /* fall through to plain-text handling */ }
      }
      return { project: line, id: '', session: '', transcript: '', ntype: '', reason: '' };
    });
}

// A key that is identical for duplicate firings of one event but differs
// between separate events. Prefer the per-request id; fall back to the
// transcript size (grows every turn); last resort a coarse time bucket.
function eventKey(kind, rec) {
  if (rec.id) {
    return kind + ':id:' + rec.id;
  }
  if (rec.transcript) {
    try {
      return kind + ':tx:' + (rec.session || '') + ':' + fs.statSync(rec.transcript).size;
    } catch (e) { /* transcript gone - fall through */ }
  }
  const win = retentionMs() || 1000;
  return kind + ':t:' + (rec.session || rec.project || '') + ':' + Math.floor(Date.now() / win);
}

// Cross-window "have we already sent this event?" gate. Creating the marker is
// atomic (wx), so among all windows exactly one wins for a given key.
function claimEventMarker(key) {
  const ttl = retentionMs();
  if (ttl === 0) {
    return true; // dedup disabled
  }
  const hash = crypto.createHash('sha1').update(key).digest('hex').slice(0, 16);
  const marker = path.join(claudeDir, MARKER_PREFIX + hash);
  try {
    const st = fs.statSync(marker);
    if (Date.now() - st.mtimeMs < ttl) {
      return false; // recently sent by some window
    }
    try { fs.unlinkSync(marker); } catch (e) { /* recycled elsewhere */ }
  } catch (e) { /* no marker yet */ }
  try {
    fs.closeSync(fs.openSync(marker, 'wx'));
    return true;
  } catch (e) {
    return false; // lost the race to another window
  }
}

function sweepMarkers() {
  const ttl = retentionMs();
  if (ttl === 0) {
    return;
  }
  let names;
  try {
    names = fs.readdirSync(claudeDir);
  } catch (e) {
    return;
  }
  names.forEach(function (n) {
    if (n.indexOf(MARKER_PREFIX) !== 0) {
      return;
    }
    const fp = path.join(claudeDir, n);
    try {
      if (Date.now() - fs.statSync(fp).mtimeMs > ttl) {
        fs.unlinkSync(fp);
      }
    } catch (e) { /* ignore */ }
  });
}

// Publish via ntfy's JSON endpoint (POST to the server root with a JSON body).
// JSON body is UTF-8, so title and message keep Cyrillic intact - no
// HTTP-header encoding issues, no curl.
//
// Returns a Promise that resolves on a 2xx response and rejects otherwise
// (bad config, network error, timeout, or non-2xx status). Callers that only
// fire-and-forget can ignore the rejection with .catch(() => {}).
function sendNotification(kind, project, interrupted, overrideMessage) {
  return new Promise(function (resolve, reject) {
    const c = cfg();
    const topic = String(c.get('topic', '') || '').trim();
    if (!topic) {
      reject(new Error('no-topic'));
      return;
    }

    let server = String(c.get('server', 'https://ntfy.sh') || 'https://ntfy.sh').trim();
    if (!/\/$/.test(server)) {
      server += '/';
    }

    let url;
    try {
      url = new URL(server);
    } catch (e) {
      reject(new Error('bad-server'));
      return;
    }

    let rawMessage;
    if (overrideMessage) {
      rawMessage = overrideMessage;
    } else if (kind === WAITING) {
      rawMessage = c.get('waitingMessage', 'Ожидание ответа');
    } else if (interrupted) {
      rawMessage = c.get('interruptedMessage', 'Запрос прерван');
    } else {
      rawMessage = c.get('message', 'Запрос завершён');
    }

    const data = {
      topic: topic,
      title: applyPlaceholders(c.get('title', 'Claude Code · {project}'), project),
      message: applyPlaceholders(rawMessage, project),
    };
    if (!data.title) {
      delete data.title; // empty title -> let ntfy fall back to the topic
    }

    const priorityName = String(c.get('priority', 'default') || 'default');
    if (PRIORITY_MAP[priorityName] && priorityName !== 'default') {
      data.priority = PRIORITY_MAP[priorityName];
    }

    const tags = String(c.get('tags', '') || '')
      .split(',')
      .map(function (t) { return t.trim(); })
      .filter(function (t) { return t.length > 0; });
    if (tags.length > 0) {
      data.tags = tags;
    }

    const click = String(c.get('click', '') || '').trim();
    if (click) {
      data.click = click;
    }

    const body = Buffer.from(JSON.stringify(data), 'utf8');
    const headers = {
      'Content-Type': 'application/json; charset=utf-8',
      'Content-Length': body.length,
    };

    const token = String(c.get('token', '') || '').trim();
    if (token) {
      headers['Authorization'] = 'Bearer ' + token;
    }

    const mod = url.protocol === 'http:' ? http : https;
    const options = {
      method: 'POST',
      hostname: url.hostname,
      port: url.port || (url.protocol === 'http:' ? 80 : 443),
      path: url.pathname || '/',
      headers: headers,
    };

    const req = mod.request(options, function (res) {
      const ok = res.statusCode >= 200 && res.statusCode < 300;
      res.resume();
      res.on('end', function () {
        if (ok) {
          resolve({ status: res.statusCode });
        } else {
          reject(new Error('http-' + res.statusCode));
        }
      });
    });
    req.on('error', function (err) { reject(err); });
    req.setTimeout(REQUEST_TIMEOUT_MS, function () {
      req.destroy(new Error('timeout'));
    });
    req.write(body);
    req.end();
  });
}

// Turn an error from sendNotification() into a short Russian explanation for
// the test command.
function describeError(err) {
  const msg = err && err.message ? err.message : String(err);
  if (msg === 'no-topic') {
    return 'не задан топик (claudeNotify.topic).';
  }
  if (msg === 'bad-server') {
    return 'некорректный адрес сервера (claudeNotify.server).';
  }
  if (msg === 'timeout') {
    return 'сервер не ответил вовремя (таймаут).';
  }
  if (/^http-4\d\d$/.test(msg)) {
    return 'сервер отклонил запрос (' + msg.slice(5) + '). Проверьте топик и токен.';
  }
  if (/^http-5\d\d$/.test(msg)) {
    return 'ошибка на стороне сервера (' + msg.slice(5) + ').';
  }
  if (err && (err.code === 'ENOTFOUND' || err.code === 'EAI_AGAIN')) {
    return 'не удалось найти сервер (нет сети или опечатка в адресе).';
  }
  if (err && err.code === 'ECONNREFUSED') {
    return 'сервер отказал в соединении.';
  }
  return 'сеть недоступна или сервер не отвечает.';
}

// Exactly-once across multiple VS Code windows for a single trigger *file*: the
// first extension instance to atomically rename it away "wins"; the others'
// rename fails. Returns the file's contents, or null if another window claimed
// it first.
function claimTrigger(kind) {
  const tPath = triggerPath(kind);
  const claim =
    tPath + '.claim-' + process.pid + '-' + Math.random().toString(36).slice(2);
  try {
    fs.renameSync(tPath, claim);
  } catch (e) {
    return null;
  }
  let content = '';
  try {
    content = fs.readFileSync(claim, 'utf8');
  } catch (e) { /* unreadable - treat as empty */ }
  try {
    fs.unlinkSync(claim);
  } catch (e) { /* ignore */ }
  return content;
}

function handleTrigger(kind) {
  const content = claimTrigger(kind);
  if (content === null) {
    return;
  }
  if (!isEnabled()) {
    return;
  }
  if (kind === WAITING && !cfg().get('notifyOnWaiting', true)) {
    return;
  }
  const seen = {};
  parseTrigger(content).forEach(function (rec) {
    if (kind === WAITING && rec.ntype && SKIP_NTYPES[rec.ntype]) {
      return;
    }
    const key = eventKey(kind, rec);
    if (seen[key]) {
      return; // duplicate within this same batch
    }
    seen[key] = true;
    if (!claimEventMarker(key)) {
      return; // another window already sent this event
    }
    const interrupted =
      kind === DONE && rec.reason && rec.reason !== 'end_turn';
    sendNotification(kind, projectName(rec.project), interrupted).catch(function () {
      /* offline / bad config - stay silent */
    });
  });
}

// Watch ~/.claude for the trigger files. fs.watch is fast but can miss events
// or report a null filename on some platforms, and it throws if ~/.claude does
// not exist yet - so back it up with a low-frequency existence poll that also
// (re)establishes the watch once the directory appears and sweeps old markers.
function startWatching(context) {
  let watcher = null;
  let tick = 0;
  const kinds = Object.keys(TRIGGERS);

  function tryWatch() {
    if (watcher) {
      return;
    }
    try {
      watcher = fs.watch(claudeDir, function (eventType, filename) {
        kinds.forEach(function (kind) {
          if (!filename || filename === TRIGGERS[kind]) {
            handleTrigger(kind);
          }
        });
      });
      watcher.on('error', function () {
        try { watcher.close(); } catch (e) { /* ignore */ }
        watcher = null;
      });
    } catch (e) {
      watcher = null; // directory missing - the poll will retry
    }
  }

  tryWatch();

  const poll = setInterval(function () {
    tryWatch();
    kinds.forEach(function (kind) {
      if (fs.existsSync(triggerPath(kind))) {
        handleTrigger(kind);
      }
    });
    if (++tick % SWEEP_EVERY_TICKS === 0) {
      sweepMarkers();
    }
  }, POLL_INTERVAL_MS);

  context.subscriptions.push({
    dispose: function () {
      if (watcher) {
        try { watcher.close(); } catch (e) { /* ignore */ }
      }
      clearInterval(poll);
    },
  });
}

// --- Hook setup -------------------------------------------------------------

function writeHookScript() {
  try {
    fs.mkdirSync(claudeDir, { recursive: true });
  } catch (e) { /* may already exist */ }
  try {
    fs.writeFileSync(hookScriptPath, HOOK_SCRIPT, 'utf8');
  } catch (e) { /* best-effort */ }
}

function hasBash() {
  const known = [
    'C:\\Program Files\\Git\\bin\\bash.exe',
    'C:\\Program Files (x86)\\Git\\bin\\bash.exe',
  ];
  for (let i = 0; i < known.length; i++) {
    if (fs.existsSync(known[i])) {
      return true;
    }
  }
  return String(process.env.PATH || '')
    .split(path.delimiter)
    .some(function (dir) {
      return dir && fs.existsSync(path.join(dir, 'bash.exe'));
    });
}

// Both variants run the helper script via node; the script itself reads the
// hook payload, so the command stays short and identical in spirit per OS.
function hookCommands() {
  if (process.platform === 'win32' && !hasBash()) {
    const s = '"$env:USERPROFILE\\.claude\\claude-notify-hook.js"';
    return {
      shell: 'powershell',
      done: 'node ' + s + ' done',
      waiting: 'node ' + s + ' waiting',
    };
  }
  const s = '"$HOME/.claude/claude-notify-hook.js"';
  return {
    shell: 'bash',
    done: 'node ' + s + ' done || true',
    waiting: 'node ' + s + ' waiting || true',
  };
}

// A hook command is ours if it references our trigger file or helper script.
function isOurHook(command) {
  return (
    typeof command === 'string' &&
    (command.indexOf('ntfy-trigger') !== -1 ||
      command.indexOf('claude-notify-hook') !== -1)
  );
}

// Drop our previous hooks for this event (keeping anyone else's, even inside a
// shared group) and append a fresh one.
function applyHook(hooks, event, shell, command, matcher) {
  const list = Array.isArray(hooks[event]) ? hooks[event] : [];
  const cleaned = [];
  list.forEach(function (group) {
    if (!group || !Array.isArray(group.hooks)) {
      cleaned.push(group);
      return;
    }
    const kept = group.hooks.filter(function (h) {
      return !(h && isOurHook(h.command));
    });
    if (kept.length > 0) {
      cleaned.push(Object.assign({}, group, { hooks: kept }));
    }
  });
  const group = {
    hooks: [{ type: 'command', shell: shell, async: true, command: command }],
  };
  if (matcher) {
    group.matcher = matcher;
  }
  cleaned.push(group);
  hooks[event] = cleaned;
}

function setupHooks() {
  writeHookScript();

  let raw = '';
  let data = {};
  if (fs.existsSync(settingsPath)) {
    try {
      raw = fs.readFileSync(settingsPath, 'utf8');
    } catch (e) {
      vscode.window.showErrorMessage(
        'Claude Notify: не удалось прочитать ~/.claude/settings.json.'
      );
      return;
    }
    if (raw.trim()) {
      try {
        data = JSON.parse(raw);
      } catch (e) {
        vscode.window.showErrorMessage(
          'Claude Notify: в ~/.claude/settings.json невалидный JSON — исправьте его и повторите.'
        );
        return;
      }
    }
  }

  if (raw) {
    try {
      fs.writeFileSync(settingsPath + '.backup', raw, 'utf8');
    } catch (e) { /* backup is best-effort */ }
  }

  if (!data.hooks || typeof data.hooks !== 'object' || Array.isArray(data.hooks)) {
    data.hooks = {};
  }
  const cmds = hookCommands();
  applyHook(data.hooks, 'Stop', cmds.shell, cmds.done);
  applyHook(data.hooks, 'Notification', cmds.shell, cmds.waiting);
  applyHook(data.hooks, 'PreToolUse', cmds.shell, cmds.waiting, 'AskUserQuestion');

  try {
    fs.writeFileSync(settingsPath, JSON.stringify(data, null, 2) + '\n', 'utf8');
  } catch (e) {
    vscode.window.showErrorMessage(
      'Claude Notify: не удалось записать ~/.claude/settings.json.'
    );
    return;
  }

  vscode.window.showInformationMessage(
    'Claude Notify: хуки записаны в ~/.claude/settings.json (' + cmds.shell +
      '). Прежняя версия сохранена как settings.json.backup. ' +
      'Перезапустите сессию Claude Code, чтобы хуки применились.'
  );
}

// --- Activation -------------------------------------------------------------

function activate(context) {
  writeHookScript();

  const item = vscode.window.createStatusBarItem(
    vscode.StatusBarAlignment.Right,
    100
  );
  item.name = 'Claude Notify';
  item.command = 'claudeNotify.toggle';
  render(item);
  item.show();
  context.subscriptions.push(item);

  // Drop any stale triggers left over from a session when no window was open.
  Object.keys(TRIGGERS).forEach(function (kind) {
    try {
      fs.unlinkSync(triggerPath(kind));
    } catch (e) { /* nothing to clean */ }
  });
  sweepMarkers();

  context.subscriptions.push(
    vscode.commands.registerCommand('claudeNotify.toggle', async function () {
      const c = cfg();
      const now = c.get('enabled', true);
      await c.update('enabled', !now, vscode.ConfigurationTarget.Global);
      render(item);
    })
  );

  context.subscriptions.push(
    vscode.commands.registerCommand('claudeNotify.test', async function () {
      const topic = String(cfg().get('topic', '') || '').trim();
      if (!topic) {
        vscode.window.showWarningMessage(
          'Claude Notify: задайте топик в настройках (claudeNotify.topic), тогда уведомления заработают.'
        );
        return;
      }
      const folders = vscode.workspace.workspaceFolders;
      const project = folders && folders.length > 0 ? folders[0].name : '';
      try {
        await sendNotification(DONE, project, false, 'Тестовое уведомление');
        vscode.window.setStatusBarMessage(
          'Claude Notify: тестовое уведомление отправлено ✓',
          4000
        );
      } catch (err) {
        vscode.window.showErrorMessage(
          'Claude Notify: не удалось отправить — ' + describeError(err)
        );
      }
    })
  );

  context.subscriptions.push(
    vscode.commands.registerCommand('claudeNotify.setupHook', function () {
      setupHooks();
      render(item);
    })
  );

  context.subscriptions.push(
    vscode.workspace.onDidChangeConfiguration(function (e) {
      if (e.affectsConfiguration('claudeNotify')) {
        render(item);
      }
    })
  );

  startWatching(context);
}

function deactivate() {}

module.exports = { activate, deactivate };
